//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEMinutes.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnteredPeMinute
    {
        public int ID { get; set; }
        public string TeacherName { get; set; }
        public Nullable<int> Minutes { get; set; }
        public Nullable<int> BadgeNumber { get; set; }
        public string School { get; set; }
        public string Grade { get; set; }
        public string Activity { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string SubstituteName { get; set; }
        public Nullable<int> IsApproved { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveTime { get; set; }
    }
}
