//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEMinutes.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEMinutesTeacherCount
    {
        public string Organization_Name { get; set; }
        public Nullable<int> TEACHER { get; set; }
    }
}
