//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEMinutes.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolTeachersWithADLogin
    {
        public string Organization_Name { get; set; }
        public string TYPE { get; set; }
        public string ABBREV_NAME { get; set; }
        public decimal SCHOOL_YEAR { get; set; }
        public string COURSE_TITLE { get; set; }
        public decimal PERIOD_BEGIN { get; set; }
        public Nullable<decimal> MAX_STUDENTS { get; set; }
        public System.Guid SECTION_GU { get; set; }
        public string ROOM_SIMPLE { get; set; }
        public string TeacherLastName { get; set; }
        public string TeacherFirstName { get; set; }
        public string BADGE_NUM { get; set; }
        public System.Guid PERSON_GU { get; set; }
        public Nullable<long> rn { get; set; }
        public string LOGIN_NAME { get; set; }
        public long aId { get; set; }
    }
}
