//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEMinutes.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolTeachersWithADLogin
    {
        public int ID { get; set; }
        public string JOB_TITLE { get; set; }
        public string Organization_Name { get; set; }
        public string TYPE { get; set; }
        public string ABBREV_NAME { get; set; }
        public string SCHOOL_YEAR { get; set; }
        public string COURSE_TITLE { get; set; }
        public string PERIOD_BEGIN { get; set; }
        public string MAX_STUDENTS { get; set; }
        public string SECTION_GU { get; set; }
        public string TeacherLastName { get; set; }
        public string TeacherFirstName { get; set; }
        public string BADGE_NUM { get; set; }
        public string PERSON_GU { get; set; }
        public string rn { get; set; }
        public string LOGIN_NAME { get; set; }
        public string aId { get; set; }
    }
}
