//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PEMinutes.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolToPrincipal
    {
        public string ORGANIZATION_NAME { get; set; }
        public string SchoolAddress { get; set; }
        public string Principal { get; set; }
        public string adLoginName { get; set; }
        public string BADGE_NUM { get; set; }
    }
}
